# render.yaml for RFID Library Application on Render.com

services:
  - type: web
    name: rfid-library
    runtime: node
    repo: https://github.com/your-username/your-repo.git  # Replace with your GitHub repo URL
    branch: main  # Replace with your branch name if different
    region: oregon  # Adjust to your preferred region (e.g., frankfurt)
    plan: free  # Use 'starter' or higher for paid plans if needed
    numInstances: 1  # Default scaling; adjust if needed
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false  # Set this in Render Dashboard (MongoDB Atlas URI)
    rootDir: .  # Assumes server.js, package.json, and public/ are at repo root